name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b3b70947e0d60be2e5f442dd1a3901c675f6abc9e81c0e66685005241e41fbd"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
