name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f21b51a03144468efac19dae3f8fea6faef8c082e6578f3d6dad1287ba9a6992"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
