name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51bad510f2cd203f0e2ecc1dbf965c1d57ba17a3357553a46568e98b200ed1a3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
